import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
        colors: {
            "primary": "#000000",
            "pale-green": "#EDFCE9",
            "surface-container-highest": "#e5e2e2",
            "tertiary-fixed": "#ebe1d5",
            "error-container": "#ffdad6",
            "on-primary": "#FFFFFF",
            "surface-bright": "#fdf8f8",
            "form-focus": "#9B60AA",
            "coral-soft": "#FFAD9B",
            "surface-container": "#f1eded",
            "action-blue": "#1863DC",
            "coral": "#FF7759",
            "on-primary-fixed": "#1b1b20",
            "surface-tint": "#5f5e64",
            "secondary-container": "#b8ede0",
            "muted": "#93939F",
            "on-primary-container": "#848389",
            "tertiary-fixed-dim": "#cec5ba",
            "surface-container-lowest": "#ffffff",
            "secondary": "#35675d",
            "on-primary-fixed-variant": "#47464c",
            "on-error": "#ffffff",
            "tertiary": "#000000",
            "focus-blue": "#4C6EE6",
            "tertiary-container": "#1f1b14",
            "background": "#fdf8f8",
            "on-secondary-container": "#3b6d63",
            "cohere-black": "#000000",
            "outline": "#78767b",
            "slate": "#75758A",
            "on-tertiary-container": "#8a8379",
            "ink": "#212121",
            "primary-fixed": "#e4e1e8",
            "primary-fixed-dim": "#c8c5cc",
            "on-secondary-fixed-variant": "#1b4f45",
            "surface-container-low": "#f7f3f3",
            "on-surface": "#1c1b1c",
            "on-surface-variant": "#47464b",
            "secondary-fixed": "#b8ede0",
            "border-light": "#E5E7EB",
            "hairline": "#D9D9DD",
            "body-muted": "#616161",
            "surface-dim": "#ddd9d9",
            "inverse-primary": "#c8c5cc",
            "dark-navy": "#071829",
            "on-tertiary-fixed": "#1f1b14",
            "on-error-container": "#93000a",
            "on-tertiary": "#ffffff",
            "error": "#B30000",
            "primary-container": "#1b1b20",
            "secondary-fixed-dim": "#9dd1c4",
            "surface": "#fdf8f8",
            "surface-container-high": "#ebe7e7",
            "outline-variant": "#c8c5cb",
            "soft-stone": "#EEECE7",
            "on-secondary-fixed": "#00201b",
            "canvas": "#FFFFFF",
            "inverse-surface": "#313030",
            "inverse-on-surface": "#f4f0f0",
            "on-secondary": "#ffffff",
            "card-border": "#F2F2F2",
            "pale-blue": "#F1F5FF",
            "on-background": "#1c1b1c",
            "on-tertiary-fixed-variant": "#4c463d",
            "surface-variant": "#e5e2e2"
        },
        borderRadius: {
            "xs": "0.25rem",
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        spacing: {
            "gutter": "24px",
            "xl": "24px",
            "md": "12px",
            "section": "80px",
            "lg": "16px",
            "margin-desktop": "64px",
            "xxs": "2px",
            "xxl": "32px",
            "xs": "6px",
            "sm": "8px",
            "margin-mobile": "20px"
        },
        fontFamily: {
            "body-large": ["Unica77 Cohere Web", "sans-serif"],
            "body": ["Unica77 Cohere Web", "sans-serif"],
            "micro": ["Unica77 Cohere Web", "sans-serif"],
            "caption": ["Unica77 Cohere Web", "sans-serif"],
            "section-display": ["Unica77 Cohere Web", "sans-serif"],
            "product-display": ["Playfair Display", "serif"],
            "card-heading": ["Unica77 Cohere Web", "sans-serif"],
            "button": ["Unica77 Cohere Web", "sans-serif"],
            "mono-label": ["JetBrains Mono", "monospace"],
            "hero-display": ["Playfair Display", "serif"],
            "feature-heading": ["Unica77 Cohere Web", "sans-serif"],
            "section-heading": ["Unica77 Cohere Web", "sans-serif"],
            "hero-display-mobile": ["Geist", "sans-serif"]
        },
        fontSize: {
            "body-large": ["18px", {"lineHeight": "1.4", "fontWeight": "400"}],
            "body": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
            "micro": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
            "caption": ["14px", {"lineHeight": "1.4", "fontWeight": "400"}],
            "section-display": ["60px", {"lineHeight": "1", "letterSpacing": "-1.2px", "fontWeight": "400"}],
            "product-display": ["72px", {"lineHeight": "1", "letterSpacing": "-1.44px", "fontWeight": "400"}],
            "card-heading": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.32px", "fontWeight": "400"}],
            "button": ["14px", {"lineHeight": "1.71", "fontWeight": "500"}],
            "mono-label": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.28px", "fontWeight": "400"}],
            "hero-display": ["96px", {"lineHeight": "1", "letterSpacing": "-1.92px", "fontWeight": "400"}],
            "feature-heading": ["24px", {"lineHeight": "1.3", "fontWeight": "400"}],
            "section-heading": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.48px", "fontWeight": "400"}],
            "hero-display-mobile": ["56px", {"lineHeight": "1.1", "letterSpacing": "-1.12px", "fontWeight": "400"}]
        }
        },
    },
    plugins: [],
};
export default config;